### ISSUE TITLE
random_weights() missing 1 required positional argument: 'population_size'

### ISSUE THREAD

**Issue by eigeneko** [Project-Platypus/Platypus#58]
Hi! dhadka

- Platypus works fine in my own laptop with ubuntu 17.04 but can't run MOEAD in a server with ubuntu 16.04, python 3.6.5 or python 3.5.2
- I only changed the algorithm from NSGAII to MOEAD in example/simple.py
- It seems that MOEA/D failed to run with `random_weights()` 

may be function `only_keys_for` doesn't work  under my operating system? 
here is the error message.

```
Traceback (most recent call last):  File "/home/zhangqihao/Platypus/examples/simple.py", line 10, in <module>
    algorithm.run(10000)
  File "/usr/local/lib/python3.6/dist-packages/Platypus_Opt-1.0.2-py3.6.egg/platypus/core.py", line 405, in run
    self.step()
  File "/usr/local/lib/python3.6/dist-packages/Platypus_Opt-1.0.2-py3.6.egg/platypus/algorithms.py", line 64, in step
    self.initialize()
  File "/usr/local/lib/python3.6/dist-packages/Platypus_Opt-1.0.2-py3.6.egg/platypus/algorithms.py", line 495, in initi
alize
    self.weights = self.weight_generator(self.problem.nobjs, **self.weight_generator_kwargs)
TypeError: random_weights() missing 1 required positional argument: 'population_size'
```

**Comment by dhadka** [comment]
Thanks for reporting this!

You're seeing this error because MOEA/D can use different weight generators, and these generators require different arguments.  When using random_weights, you need to specify population_size:

    algorithm = MOEAD(problem, population_size=100)

I'll put in a fix so it uses a default value so the behavior is similar to other algorithms.

**Comment by dhadka** [comment]
Fix is in 2269819
